import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";

// UI디자인이 통째로 Noto Sans KR 로 그려져 있다 — 본문·부제 400/500, 제목과
// tertiary 버튼 700. subsets 는 preload 대상만 정하는 값이라 latin 만 적어도
// 한글 글리프는 같은 CSS 로 따라온다(요청 URL 에 subset 파라미터가 없다).
const notoSansKr = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ko"
      className={`${notoSansKr.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
